upstream timestable_backend {
    server unix:/run/uvicorn-timestable/fastapi-timestable.sock fail_timeout=0;
}
server {
  client_max_body_size 100M;
  sendfile on;
  default_type application/octet-stream;

  server_name 1x1.rempfer.eu;

  gzip on;
  gzip_http_version 1.1;
  gzip_disable      "MSIE [1-6]\.";
  gzip_min_length   256;
  gzip_vary         on;
  gzip_proxied      expired no-cache no-store private auth;
  gzip_types        text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;
  gzip_comp_level   9;

  location /api {
    proxy_pass http://timestable_backend;
  #  proxy_http_version 1.1;
  #  proxy_set_header Upgrade $http_upgrade;
  #  proxy_set_header Connection 'upgrade';
  #  proxy_set_header Host $host;
  #  proxy_cache_bypass $http_upgrade;
  }

  location / {
    root /var/www/timestable/frontend/;
    try_files $uri $uri/ /index.html;

    location ~ /index.html$|.*\.json$ {
      add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
    }

    location ~ .*\.css$|.*\.js$ {
      add_header Cache-Control 'max-age=31449600'; # one year
    }

    location ~* \.(?:jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc)$ {
      expires 1M; # one month
    }
  }


    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/1x1.rempfer.eu/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/1x1.rempfer.eu/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

server {
    if ($host = 1x1.rempfer.eu) {
        return 301 https://$host$request_uri;
    } # managed by Certbot



  server_name 1x1.rempfer.eu;
    listen 80;
    return 404; # managed by Certbot


}
