-- This file is simultaneously used to initialize an empty database from scratch
-- and to migrate an existing database from the old schema to the new one. It should be
-- idempotent, meaning that running it multiple times should not cause errors or change
-- the database after the first run.

create extension if not exists pgcrypto;

create table if not exists children (
  id_transparent int not null primary key GENERATED BY DEFAULT AS IDENTITY,
  id_obfuscated bytea unique default gen_random_bytes(8),
  created_at timestamp not null default now()
);

alter table children
  alter column id_obfuscated set default gen_random_bytes(8);

create index if not exists children_id_obfuscated_idx
  on children (id_obfuscated);

GRANT ALL PRIVILEGES ON TABLE children TO timestable;


DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM pg_class
    WHERE relname = 'child_answers'
      AND relkind = 'r'
  ) AND NOT EXISTS (
    SELECT 1
    FROM pg_class
    WHERE relname = 'answers_timestable'
      AND relkind = 'r'
  ) THEN
    ALTER TABLE child_answers RENAME TO answers_timestable;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM pg_class
    WHERE relname = 'child_answers_child_id_transparent_idx'
      AND relkind = 'i'
  ) AND NOT EXISTS (
    SELECT 1
    FROM pg_class
    WHERE relname = 'answers_timestable_child_id_transparent_idx'
      AND relkind = 'i'
  ) THEN
    ALTER INDEX child_answers_child_id_transparent_idx
      RENAME TO answers_timestable_child_id_transparent_idx;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM pg_class
    WHERE relname = 'child_answers_child_id_transparent_answered_at_desc_idx'
      AND relkind = 'i'
  ) AND NOT EXISTS (
    SELECT 1
    FROM pg_class
    WHERE relname = 'answers_timestable_child_id_transparent_answered_at_desc_idx'
      AND relkind = 'i'
  ) THEN
    ALTER INDEX child_answers_child_id_transparent_answered_at_desc_idx
      RENAME TO answers_timestable_child_id_transparent_answered_at_desc_idx;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM pg_class
    WHERE relname = 'child_answers_child_question_answered_at_desc_idx'
      AND relkind = 'i'
  ) AND NOT EXISTS (
    SELECT 1
    FROM pg_class
    WHERE relname = 'answers_timestable_child_question_answered_at_desc_idx'
      AND relkind = 'i'
  ) THEN
    ALTER INDEX child_answers_child_question_answered_at_desc_idx
      RENAME TO answers_timestable_child_question_answered_at_desc_idx;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM pg_class
    WHERE relname = 'child_answers_pkey'
      AND relkind = 'i'
  ) AND NOT EXISTS (
    SELECT 1
    FROM pg_class
    WHERE relname = 'answers_timestable_pkey'
      AND relkind = 'i'
  ) THEN
    ALTER INDEX child_answers_pkey
      RENAME TO answers_timestable_pkey;
  END IF;
END $$;

create table if not exists answers_timestable (
  child_id_transparent int not null REFERENCES children(id_transparent),
  question_id smallint not null, -- a*b gets id a*11+b
  correct boolean not null,
  answered_at timestamp not null default now(),
  primary key (child_id_transparent, question_id, answered_at)
);

create index if not exists answers_timestable_child_id_transparent_idx
  on answers_timestable (child_id_transparent);

create index if not exists answers_timestable_child_id_transparent_answered_at_desc_idx
  on answers_timestable (child_id_transparent, answered_at desc);

create index if not exists answers_timestable_child_question_answered_at_desc_idx
  on answers_timestable (child_id_transparent, question_id, answered_at desc);

GRANT ALL PRIVILEGES ON TABLE answers_timestable TO timestable;

create table if not exists answers_timestable_equations (
  child_id_transparent int not null REFERENCES children(id_transparent),
  question_id smallint not null, -- a*b gets id a*11+b
  correct boolean not null,
  answered_at timestamp not null default now(),
  primary key (child_id_transparent, question_id, answered_at)
);

create index if not exists answers_timestable_equations_child_id_transparent_idx
  on answers_timestable_equations (child_id_transparent);

create index if not exists answers_timestable_equations_child_id_transparent_answered_at_desc_idx
  on answers_timestable_equations (child_id_transparent, answered_at desc);

create index if not exists answers_timestable_equations_child_question_answered_at_desc_idx
  on answers_timestable_equations (child_id_transparent, question_id, answered_at desc);

GRANT ALL PRIVILEGES ON TABLE answers_timestable_equations TO timestable;

create table if not exists answers_plustable (
  child_id_transparent int not null REFERENCES children(id_transparent),
  question_id smallint not null, -- a+b gets id a*11+b
  correct boolean not null,
  answered_at timestamp not null default now(),
  primary key (child_id_transparent, question_id, answered_at)
);

create index if not exists answers_plustable_child_id_transparent_idx
  on answers_plustable (child_id_transparent);

create index if not exists answers_plustable_child_id_transparent_answered_at_desc_idx
  on answers_plustable (child_id_transparent, answered_at desc);

create index if not exists answers_plustable_child_question_answered_at_desc_idx
  on answers_plustable (child_id_transparent, question_id, answered_at desc);

GRANT ALL PRIVILEGES ON TABLE answers_plustable TO timestable;

create table if not exists answers_plustable_equations (
  child_id_transparent int not null REFERENCES children(id_transparent),
  question_id smallint not null, -- a+b gets id a*11+b
  correct boolean not null,
  answered_at timestamp not null default now(),
  primary key (child_id_transparent, question_id, answered_at)
);

create index if not exists answers_plustable_equations_child_id_transparent_idx
  on answers_plustable_equations (child_id_transparent);

create index if not exists answers_plustable_equations_child_id_transparent_answered_at_desc_idx
  on answers_plustable_equations (child_id_transparent, answered_at desc);

create index if not exists answers_plustable_equations_child_question_answered_at_desc_idx
  on answers_plustable_equations (child_id_transparent, question_id, answered_at desc);

GRANT ALL PRIVILEGES ON TABLE answers_plustable_equations TO timestable;

create table if not exists answers_division_remainder (
  child_id_transparent int not null REFERENCES children(id_transparent),
  question_id smallint not null, -- dividend/divisor with remainder gets id dividend*10+(divisor-1)
  correct boolean not null,
  answered_at timestamp not null default now(),
  primary key (child_id_transparent, question_id, answered_at)
);

create index if not exists answers_division_remainder_child_id_transparent_idx
  on answers_division_remainder (child_id_transparent);

create index if not exists answers_division_remainder_child_id_transparent_answered_at_desc_idx
  on answers_division_remainder (child_id_transparent, answered_at desc);

create index if not exists answers_division_remainder_child_question_answered_at_desc_idx
  on answers_division_remainder (child_id_transparent, question_id, answered_at desc);

GRANT ALL PRIVILEGES ON TABLE answers_division_remainder TO timestable;